odev4/Controllers/ComplaintsController.cs
using odev4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace odev4.Controllers
{
    public class ComplaintsController : Controller
    {
        //
        // GET: /Complaints/

        public List<Complaints> complaintsList = new List<Complaints>(){
                new Complaints(){id = 1, complaintstitle = "Şikayet 1", complaintsSubject = "Şikayet Konu 1", complaintWhy = "Şikayet Nedeni 1", date = DateTime.Now },
                new Complaints(){id = 2, complaintstitle = "Şikayet 2", complaintsSubject = "Şikayet Konu 2", complaintWhy = "Şikayet Nedeni 2", date = DateTime.Now },
                new Complaints(){id = 3, complaintstitle = "Şikayet 3", complaintsSubject = "Şikayet Konu 3", complaintWhy = "Şikayet Nedeni 3", date = DateTime.Now },
                new Complaints(){id = 4, complaintstitle = "Şikayet 4", complaintsSubject = "Şikayet Konu 4", complaintWhy = "Şikayet Nedeni 4", date = DateTime.Now },
                new Complaints(){id = 5, complaintstitle = "Şikayet 5", complaintsSubject = "Şikayet Konu 5", complaintWhy = "Şikayet Nedeni 5", date = DateTime.Now }
          };

        public ActionResult Complaints()
        {
            return View(this.complaintsList);
        }
	}
}

odev4/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using odev4.Models;

namespace odev4.Controllers
{
    public class OrdersController : Controller
    {
        //
        // GET: /Orders/
        
        public List<Orders> ordersList = new List<Orders>(){
                new Orders(){id = 1, ordesnm = "Sipariş 1", productnm = "1.Ürün", producprice = 123.00, producpiece = 1, date = DateTime.Now},
                new Orders(){id = 2, ordesnm = "Sipariş 2", productnm = "2.Ürün", producprice = 101.00, producpiece = 3, date = DateTime.Now },
                new Orders(){id = 3, ordesnm = "Sipariş 3", productnm = "3.Ürün", producprice = 50.00, producpiece = 5, date = DateTime.Now },
                new Orders(){id = 4, ordesnm = "Sipariş 4", productnm = "4.Ürün", producprice = 72.00, producpiece = 7, date = DateTime.Now },
                new Orders(){id = 5, ordesnm = "Sipariş 5", productnm = "5.Ürün", producprice = 19.00, producpiece = 9, date = DateTime.Now }
          };

        public ActionResult Orders()
        {
            return View(this.ordersList);
        }
	}
}

odev4/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using odev4.Models;

namespace odev4.Controllers
{
    public class UsersController : Controller
    {
        //
        // GET: /Users/

        public List<Users> usersList = new List<Users>(){
                new Users(){id = 1, usernm = "name 1", loginnm = "lgn1", pwd = "1", date = DateTime.Now },
                new Users(){id = 2, usernm = "name 2", loginnm = "lgn2", pwd = "2", date = DateTime.Now },
                new Users(){id = 3, usernm = "name 3", loginnm = "lgn3", pwd = "3", date = DateTime.Now },
                new Users(){id = 4, usernm = "name 4", loginnm = "lgn4", pwd = "4", date = DateTime.Now },
                new Users(){id = 5, usernm = "name 5", loginnm = "lgn5", pwd = "5", date = DateTime.Now }
          };

        public ActionResult Users()
        {
            return View(this.usersList);
        }
	}
}

odev4/Views/Shared/Counter.cshtml
<div class="alert alert-info text-center" style="margin-top:2em">Ziyaretçi Sayacı: @ViewBag.counter</div>


odev4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Paneli</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">Panel</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.ActionLink("Şikayetler", "Complaints", "Complaints")</li>
                    <li>@Html.ActionLink("Siparişler", "Orders", "Orders")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Users", "Users")</li>
                    <li>@Html.ActionLink("Hatalı Girişler", "WrongEntry", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @Session["name"]
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">                          
                                @using (Html.BeginForm("LogOff", "Home", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Çıkış</a></li>
                                }
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*<script>
        $("#close").click(function () { window.close(); });
    </script>*@
</body>
</html>